name: CI/CD Deploy FE & BE

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ahkammubarok28
  BACKEND_IMAGE: ahkammubarok28/appweb-backend-test:latest
  FRONTEND_IMAGE: ahkammubarok28/appweb-frontend-test:latest
  SSH_HOST: 13.215.254.156
  SSH_USER: ubuntu
  CONTAINER_NAME_BE: appweb-backend-test
  CONTAINER_NAME_FE: appweb-frontend-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/dockerfile.be
          push: true
          tags: ${{ env.BACKEND_IMAGE }}

      - name: Build & push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/dockerfile.fe
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su -c 'docker pull ${{ env.BACKEND_IMAGE }}'
            sudo su -c 'docker stop ${{ env.CONTAINER_NAME_BE }} || true'
            sudo su -c 'docker rm ${{ env.CONTAINER_NAME_BE }} || true'
            sudo su -c 'docker run -d --name ${{ env.CONTAINER_NAME_BE }} --restart always -p 8082:80 ${{ env.BACKEND_IMAGE }}'

            sudo su -c 'docker pull ${{ env.FRONTEND_IMAGE }}'
            sudo su -c 'docker stop ${{ env.CONTAINER_NAME_FE }} || true'
            sudo su -c 'docker rm ${{ env.CONTAINER_NAME_FE }} || true'
            sudo su -c 'docker run -d --name ${{ env.CONTAINER_NAME_FE }} --restart always -p 8081:80 ${{ env.FRONTEND_IMAGE }}'

            sudo systemctl reload nginx

